### ISSUE TITLE
Request: Adding rotation for all directions

### ISSUE THREAD

**Issue by nielsotto** [albertopiras/threeJS-object-controls#1]
Would be a great addition to have controls for rotating the chosen object in the direction of your choosing. Preferably with some boolean telling it which axis can be rotated around.

**Comment by mspacemedia** [comment]
Second that idea, with min/max on each axis to allow for finer control would be an awesome addition

**Comment by albertopiras** [comment]
Hi guys, thanks to both of you
@nielsotto  you can enable vertical rotation calling: controls.enableVerticalRotation();
@mspacemedia you can enable max horizontal and vertical angles calling  controls.setMaxVerticalRotationAngle(radiants, radiants) 
like in the online demo:
 controls.setMaxVerticalRotationAngle(Math.PI / 4, Math.PI / 4);
same thing for the horizontal rotation
setMaxHorizontalRotationAngle(radiants,radiants).

The documentation will be updated soon
