### ISSUE TITLE
Thoughts on auto rotation the mesh object?

### ISSUE THREAD

**Issue by pmkhoa** [albertopiras/threeJS-object-controls#10]
Thanks for developing this package. It works great.

I was curious if you have any plan to develop the auto rotation to the mesh? 
If that's not something you consider to add to the package, do you think it's possible to add that manually? 

Thanks!

**Comment by albertopiras** [comment]
Hi @pmkhoa ,

Sure you can do it manually, it's pretty easy:

Open the index.html file and try to replace the function animate with this
     function animate() {
            mshBox.rotation.y += 0.01; //<- here the rotation
            requestAnimationFrame(animate);
            render();
        }

Hope this helps! :)

Alberto

**Comment by pmkhoa** [comment]
@albertopiras Thank you! That worked. This actually made feel like maybe it's helpful to have the method that expose the isDragging state so that we can disable the auto rotation or other interaction when object is dragging.

**Comment by albertopiras** [comment]
@pmkhoa Sure this is a very cool idea, thanks! I'll update you 💯

**Comment by albertopiras** [comment]
@pmkhoa I've added these cool suggestions, and I also updated the example! Thanks,  and if the project helped you, thumb up! :) Bye
