### ISSUE TITLE
request to add enableDamping + dampingFactor, similar to OrbitControls

### ISSUE THREAD

**Issue by variant-tech** [albertopiras/threeJS-object-controls#11]
thanks for the handy package! Any chance you are planning on adding dampingFactor to the flow? Would help a lot with refining animations and such.

**Comment by albertopiras** [comment]
Hi!
Thanks for your feedback.
At the moment this is not in plan.
The idea is to keep the project as simple as possible, to allow developer to import and modify it according their needs :)

Bests,

Alberto
