### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'y')

### ISSUE THREAD

**Issue by avidsapp** [albertopiras/threeJS-object-controls#13]
I'm attempting to add this to a Gatsby site with `threejs` and `react-globe.gl` already functioning correctly. When adding this library I get the following error when attempting to rotate the mesh:

`Uncaught TypeError: Cannot read properties of undefined (reading 'y')` @ ObjectControls.js:193

I have also tried disabling the native `react-globe.gl` controls, but no change.

**Comment by albertopiras** [comment]
@avidsapp 
It looks like your mesh hans't the rotation property.

Consider to check[ this link](https://github.com/albertopiras/object-controls-angular-example) as an example to integrate ObjectControls module into an existing project.
