### ISSUE TITLE
Option to Pan the Scene too

### ISSUE THREAD

**Issue by mspacemedia** [albertopiras/threeJS-object-controls#3]
Would it be possible to add the OrbitControls Pan controls in to the ObjectControls javascript or is there a fundamental reason this wouldn't work?

Mark

**Comment by albertopiras** [comment]
The purpose of this project is to allow the user to move a Mesh and not the scene. Please describe the concrete case you need

**Comment by mspacemedia** [comment]
I have a product the animates (opens) at this point the top of the object can appear to fall out of the canvas area or some of the detail to be out of centre. This would necessitate the user being able to pan around the viewport to fully realise the object they are viewing.

**Comment by mspacemedia** [comment]
Note to self, fully explain the requirement. For the purposes of my requirement it would only need 2D tracking of the window, but I guess depth panning might be of use to some.

**Comment by albertopiras** [comment]
I got it. This is not possible for now, you can even move the camera manually and change the zoom level to adjust the frame you need.The purpouse of this project is to allow to interact with an Object; while the OrbitControls 's behaviour is it to move the camera. Ohterwise we should allow to interact both with the object and the camera when needed, Switching manually the control between them, but this would be an extreme case and now it is not planned to do, sorry.
