### ISSUE TITLE
Any chance we could get this as an npm module?

### ISSUE THREAD

**Issue by kyleatblackfoot** [albertopiras/threeJS-object-controls#4]
My project is set up by importing THREE via npm, I'm battling to make this work alongside that. Any ideas? Else any chance you could add it to npm?

**Comment by albertopiras** [comment]
Hi @kyleatblackfoot, thanks for your feedback, and sorry for the late reply. We are going to add the npm repo soon

**Comment by albertopiras** [comment]
Hi @kyleatblackfoot  && guys, finally we got the [npm repo](https://www.npmjs.com/package/threejs-object-controls) 🥇 
I also created a quick example about how to integrate threejs-object-controls into an Angular 2.X app!
