### ISSUE TITLE
controls.reset()

### ISSUE THREAD

**Issue by damirmur** [albertopiras/threeJS-object-controls#5]
Greetings.
OrbitControls has a function to reset to initial settings. Here, you probably need to keep a list of objects with their parameters. For resetting to initial settings, what parameters are important for a particular object?

**Comment by albertopiras** [comment]
Hi @damirmur 

There are global settings like 'rotationSpeed', 'zoomSpeed' 'zooming range distance' and so on.
Actually yours is a good tip.
If I understand correctly you suggest a reset() method able to set to the 'default' values all these interaction settings, right?

**Comment by damirmur** [comment]
First of all, I would like to reset the position of the object to its original position

**Comment by albertopiras** [comment]
I think you can already to that, simply setting the object properties manually
