### ISSUE TITLE
Move the page when scrolling the mouse wheel

### ISSUE THREAD

**Issue by damirmur** [albertopiras/threeJS-object-controls#6]
Greetings.
My scene is displayed, as it should be, not in the full window. When scrolling the mouse wheel, the page is moved first, and then only the object in the scene is removed or brought closer. How to overcome this?

**Comment by albertopiras** [comment]
Hi @damirmur,

thanks for your feedback, have you got an online example reproducing this behaviour?

**Comment by damirmur** [comment]
There is no example on GitHub, and saving the page quickly does not work completely, but you try to create a page on a computer to go beyond the height of one browser page and specify the scene dimensions less than the page width, I have a scene size (700,700)

**Comment by damirmur** [comment]
Made a quick example. I don't know how to attach an archive, so I'll try:
index.html
`<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Hello ObjectControls</title>
</head>
<body>
<br/>
<br/>
<br/>
<br/>
<br/>
    <div id="app"></div>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
      
<script>
loadScript=(src)=>{
  return new Promise(function(resolve, reject) {
    let script = document.createElement('script');
    script.src = src;
    script.onload = () => resolve(script);
    script.onerror = () => reject(new Error(`Error load script ${src}`));
    document.head.append(script);
  });
}
loadScript("three.min.js")
  .then(script => loadScript("ObjectControls.js"))
  .then(script => loadScript("index.js"))
</script>
</body>
</html>`
index.js
`sizeScene = (w = window.innerWidth, h = window.innerHeight) => {
    return {'w': w, 'h': h};
};
let size = sizeScene(800, 800);
let scene = new THREE.Scene();
scene.background = new THREE.Color('skyblue');
let resolution = new THREE.Vector2(size.w, size.h);
let camera = new THREE.PerspectiveCamera(75, resolution.x / resolution.y, 0.1, 1000);
camera.position.z = 20;
let renderer = new THREE.WebGLRenderer();
document.getElementById('app').append(renderer.domElement);
renderer.setSize(size.w, size.h);
var geometry = new THREE.BoxGeometry();
var material = new THREE.MeshBasicMaterial( { color: 0x00ff00 } );
var cube = new THREE.Mesh( geometry, material );
let controls = new ObjectControls(camera, renderer.domElement, cube);
controls.enableVerticalRotation();
controls.setDistance(1, 200);

scene.add( cube );

			camera.position.z = 5;

animate = () => {
    requestAnimationFrame(animate);
    renderer.render(scene, camera);
}
animate();`

On the page around, add a lot of <br /> around the render element.

**Comment by damirmur** [comment]
live example https://jsfiddle.net/c6gk4uae/1/

**Comment by damirmur** [comment]
On a laptop on a touchpad, when increasing, decreasing, the whole page generally increases, decreases

**Comment by albertopiras** [comment]
This behavior, is not related to ObjectControl library, but it's about a proper usage of threeJS. Take a look here https://threejs.org/docs/index.html#manual/en/introduction/Creating-a-scene
